name: PasteFlow
options:
  bundleIdPrefix: com.pasteflow
targets:
  PasteFlow:
    type: application
    platform: macOS
    deploymentTarget: "13.0"
    sources:
      - path: PasteFlow
        resources:
          - PasteFlow/Resources/Dictionaries/ru_RU.dic
          - PasteFlow/Resources/Dictionaries/ru_RU.aff
    info:
      path: PasteFlow/Info.plist
      properties:
        LSUIElement: true
    settings:
      base:
        CODE_SIGN_ENTITLEMENTS: PasteFlow.entitlements
        ENABLE_HARDENED_RUNTIME: YES
        SWIFT_VERSION: 5.9
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_STYLE: Automatic
        SWIFT_OBJC_BRIDGING_HEADER: PasteFlow/Infrastructure/Hunspell/PasteFlow-Bridging-Header.h
        CLANG_CXX_LANGUAGE_STANDARD: "c++17"
        CLANG_CXX_LIBRARY: "libc++"
        HEADER_SEARCH_PATHS: "$(SRCROOT)/PasteFlow/Infrastructure/Hunspell $(SRCROOT)/PasteFlow/Infrastructure/Hunspell/src"
